### ISSUE TITLE
Add explicit check for .fai file (reference fasta index file)

### ISSUE THREAD

**Issue by vadimzalunin** [vadimzalunin/crammer#1]
Exception is thrown when the reference fasta file is not indexed (no .fai file): 

Exception in thread "main" java.lang.UnsupportedOperationException
  at net.sf.picard.reference.AbstractFastaSequenceFile.getSequence(AbstractFastaSequenceFile.java:116)
  at net.sf.picard.reference.FastaSequenceFile.getSequence(FastaSequenceFile.java:40)
  at uk.ac.ebi.ena.sra.cram.Bam2Cram.getReferenceSequenceBases(Bam2Cram.java:116)
  at uk.ac.ebi.ena.sra.cram.Bam2Cram.compressAllRecordsForSequence(Bam2Cram.java:134)
  at uk.ac.ebi.ena.sra.cram.Bam2Cram.run(Bam2Cram.java:101)
  at uk.ac.ebi.ena.sra.cram.Bam2Cram.main(Bam2Cram.java:240)
  at uk.ac.ebi.ena.sra.cram.CramTools.main(CramTools.java:65)

Picard silently returns a no-index instance for which getSequence() method is not implemented.

**Comment by vadimzalunin** [comment]
Fixed in 0.4
