### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by www1234** [vadimzalunin/crammer#14]
> java -jar cramtools_06_reffix_30_1_12.jar bam --input-cram-file NA12882_CSS2_merged_nu_inssub.cram --reference-fasta-file HumanNCBI37Fasta.fa --output-bam-file NA12882_CSS2_merged_nu_inssub.bam

gives:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2746)
    at java.util.ArrayList.ensureCapacity(ArrayList.java:187)
    at java.util.ArrayList.add(ArrayList.java:378)
    at uk.ac.ebi.ena.sra.cram.encoding.ReadFeatureCodec.read(ReadFeatureCodec.java:78)
    at uk.ac.ebi.ena.sra.cram.encoding.ReadFeatureCodec.read(ReadFeatureCodec.java:20)
    at uk.ac.ebi.ena.sra.cram.encoding.CramRecordCodec.read(CramRecordCodec.java:91)
    at uk.ac.ebi.ena.sra.cram.encoding.CramRecordCodec.read(CramRecordCodec.java:16)
    at uk.ac.ebi.ena.sra.cram.impl.SequentialCramReader.readRecord(SequentialCramReader.java:85)
    at uk.ac.ebi.ena.sra.cram.Cram2Bam.convert(Cram2Bam.java:204)
    at uk.ac.ebi.ena.sra.cram.Cram2Bam.main(Cram2Bam.java:105)
    at uk.ac.ebi.ena.sra.cram.CramTools.main(CramTools.java:54)

**Comment by vadimzalunin** [comment]
Try increasing memory: 
java -Xmx2g cramtools...

**Comment by www1234** [comment]
> java -Xmx2g cramtools_06_reffix_30_1_12.jar 

gives:
Exception in thread "main" java.lang.NoClassDefFoundError: cramtools_06_reffix_30_1_12/jar
Caused by: java.lang.ClassNotFoundException: cramtools_06_reffix_30_1_12.jar
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:319)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:264)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:332)

**Comment by vadimzalunin** [comment]
Sorry, '-jar' is missing, it should be: 
java -Xmx2g -jar cramtools_06_reffix_30_1_12.jar ...

**Comment by www1234** [comment]
It worked. Thanks.
