### ISSUE TITLE
exception thrown with ViewSam2

### ISSUE THREAD

**Issue by tcarver** [vadimzalunin/crammer#25]
An exception is thrown with version 0.8 (it seems this is the case for any start position > 441 with this BAM):

java -Dreference=L2_cat.fasta -cp cramtools.jar net.sf.picard.sam.ViewSam2 INPUT=NV.cram AM884176.1:442-800
[Wed Apr 25 12:09:36 BST 2012] net.sf.picard.sam.ViewSam2 AM884176.1:442-800 INPUT=NV.cram    ALIGNMENT_STATUS=All PF_STATUS=All CONTAINED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Wed Apr 25 12:09:36 BST 2012] Executing as tjc on Mac OS X 10.5.8 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.6.0_26-b03-384-9M3425; Picard version: 0.8-b17
AM884176.1:442-800
[Wed Apr 25 12:09:37 BST 2012] net.sf.picard.sam.ViewSam2 done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=85000192
FAQ:  http://sourceforge.net/apps/mediawiki/picard/index.php?title=Main_Page
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 22
        at uk.ac.ebi.ena.sra.cram.io.DefaultBitInputStream.readLongBits(DefaultBitInputStream.java:99)
        at uk.ac.ebi.ena.sra.cram.encoding.HuffmanByteCodec2.read(HuffmanByteCodec2.java:82)
        at uk.ac.ebi.ena.sra.cram.encoding.HuffmanByteCodec2.read(HuffmanByteCodec2.java:17)
        at uk.ac.ebi.ena.sra.cram.encoding.CramRecordCodec.read(CramRecordCodec.java:55)
        at uk.ac.ebi.ena.sra.cram.encoding.CramRecordCodec.read(CramRecordCodec.java:19)
        at uk.ac.ebi.ena.sra.cram.impl.CramPreemptiveRandomAccessIterator.getNextRecord(CramPreemptiveRandomAccessIterator.java:232)
        at uk.ac.ebi.ena.sra.cram.impl.CramPreemptiveRandomAccessIterator.advance(CramPreemptiveRandomAccessIterator.java:215)
        at uk.ac.ebi.ena.sra.cram.impl.CramPreemptiveRandomAccessIterator.<init>(CramPreemptiveRandomAccessIterator.java:130)
        at net.sf.samtools.CRAMFileReader.query(CRAMFileReader.java:189)
        at net.sf.samtools.SAMFileReader.query(SAMFileReader.java:512)
        at net.sf.picard.sam.ViewSam2.doWork(ViewSam2.java:122)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)
        at net.sf.picard.sam.ViewSam2.main(ViewSam2.java:87)

Thanks
Tim

**Comment by vadimzalunin** [comment]
is it possible to share the file?

**Comment by tcarver** [comment]
Reference:
http://www.genedb.org/artemis/NAR/chlamydia/L2_cat.fasta.gz

BAM:
http://www.genedb.org/artemis/NAR/chlamydia/NV.bam

-Tim

**Comment by vadimzalunin** [comment]
Confirmed. The bug is in the new implementation of BitOutputStream (uk.ac.ebi.ena.sra.cram.io.LongBufferBitInputStream violates contract for hanging bits in the range 0..7) and affects only random access for indices generated with 0.8. 
I'l revert it back for now and push to git soon.

**Comment by vadimzalunin** [comment]
Hang on, something else poped up: 

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 37
        at uk.ac.ebi.ena.sra.cram.impl.RestoreBases.restoreReadBases(RestoreBases.java:72)
        at uk.ac.ebi.ena.sra.cram.impl.CramPreemptiveRandomAccessIterator.getNextRecord(CramPreemptiveRandomAccessIterator.java:239)
        at uk.ac.ebi.ena.sra.cram.impl.CramPreemptiveRandomAccessIterator.advance(CramPreemptiveRandomAccessIterator.java:215)
        at uk.ac.ebi.ena.sra.cram.impl.CramPreemptiveRandomAccessIterator.next(CramPreemptiveRandomAccessIterator.java:187)
        at uk.ac.ebi.ena.sra.cram.impl.CramPreemptiveRandomAccessIterator.next(CramPreemptiveRandomAccessIterator.java:29)
        at net.sf.samtools.CachingSAMRecordIterator.readNextCramRecord(CachingSAMRecordIterator.java:139)
        at net.sf.samtools.CachingSAMRecordIterator.next(CachingSAMRecordIterator.java:82)
        at net.sf.samtools.CachingSAMRecordIterator.next(CachingSAMRecordIterator.java:18)
        at net.sf.samtools.PreemptiveSAMRecordIterator.advance(PreemptiveSAMRecordIterator.java:60)
        at net.sf.samtools.PreemptiveSAMRecordIterator.hasNext(PreemptiveSAMRecordIterator.java:38)
        at net.sf.samtools.SAMFileReader$AssertableIterator.hasNext(SAMFileReader.java:872)
        at net.sf.picard.sam.ViewSam2.doWork(ViewSam2.java:124)
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)

**Comment by vadimzalunin** [comment]
Just pushed 0.83 with the fix. Please give it a try.

**Comment by tcarver** [comment]
Thanks for sorting that out. I have tested it and it works well.
