### ISSUE TITLE
runtime exception v0.3

### ISSUE THREAD

**Issue by calkan** [vadimzalunin/crammer#3]
Hi

I mapped one lane of human data (100bp PE; SRR034940) with BWA (default parameters), and sorted & indexed the BAM with samtools. Crammer gives an exception:

 java -d64 -jar cramtools.jar cram --input-bam-file SRR034940.sort.bam  --reference-fasta-file hg19.fasta --output-cram-file SRR034940.sort.cram

DEBUG CramWriter - Block purged: 100000 3961653 39.62   0.3962
Exception in thread "main" java.lang.RuntimeException: Illegal base at 60830533: 77
    at uk.ac.ebi.ena.sra.cram.Utils.capitaliseAndCheckBases(Utils.java:207)
    at uk.ac.ebi.ena.sra.cram.Bam2Cram.getReferenceSequenceBases(Bam2Cram.java:150)
    at uk.ac.ebi.ena.sra.cram.Bam2Cram.compressAllRecordsForSequence(Bam2Cram.java:164)
    at uk.ac.ebi.ena.sra.cram.Bam2Cram.run(Bam2Cram.java:136)
    at uk.ac.ebi.ena.sra.cram.Bam2Cram.main(Bam2Cram.java:296)
    at uk.ac.ebi.ena.sra.cram.CramTools.main(CramTools.java:66)

thx.

**Comment by calkan** [comment]
My guess is that this is due to the non-ACGT bases present in hg19:

> chr3:60830530-60830536
> CTGMCT

**Comment by vadimzalunin** [comment]
Confirmed. 
The new version (0.5) should take care of that.

**Comment by vadimzalunin** [comment]
Non-issue in v0.3
Behaviour changed in v0.5
