### ISSUE TITLE
Unknown base when calcualting base transition: M

### ISSUE THREAD

**Issue by vadimzalunin** [vadimzalunin/crammer#32]
Conversion to cram for the chromosome 20 BAMs completes okay, however none of the conversions for the mapped bams complete.There appear to be 2 separate errors.

For example, ftp://ftp.1000genomes.ebi.ac.uk//vol1/ftp/data/HG00273/alignment/HG00273.mapped.ILLUMINA.bwa.FIN.low_coverage.20111114.bam

Exception in thread "main" java.lang.IllegalArgumentException: Unknown base when calcualting base transition: M
        at net.sf.cram.encoding.read_features.BaseTransitions.getBaseTransition(BaseTransitions.java:186)
        at net.sf.cram.encoding.read_features.BaseChange.toInt(BaseChange.java:22)
        at net.sf.cram.encoding.read_features.BaseChange.<init>(BaseChange.java:14)
        at net.sf.cram.Sam2CramRecordFactory.addSubstitutionsAndMaskedBases(Sam2CramRecordFactory.java:369)
        at net.sf.cram.Sam2CramRecordFactory.createVariations(Sam2CramRecordFactory.java:285)
        at net.sf.cram.Sam2CramRecordFactory.checkedCreateVariations(Sam2CramRecordFactory.java:220)
        at net.sf.cram.Sam2CramRecordFactory.createCramRecord(Sam2CramRecordFactory.java:159)
        at net.sf.cram.Bam2Cram.convert(Bam2Cram.java:102)
        at net.sf.cram.Bam2Cram.main(Bam2Cram.java:266)
        at net.sf.cram.CramTools.main(CramTools.java:72)

**Comment by ghuls** [comment]
An error that is probably related:

Test done with last git version (ab6c672ac25e14c440275d86f73b8a06d157c2af):

Conversion from BAM to CRAM ==> OK

Converting CRAM back to BAM ==> FAILS: Unknown reference base when restoring base from transition: g, 0

```
$ time java -jar /software/cram/cram-git/cramtools-1.0.jar bam --input-cram-file test-tophat2-transcriptome.dedup.cram --reference-fasta-file /resources/human/hg19/Homo_sapiens_assembly19_sorted.fasta --output-bam-file test-tophat2-transcriptome.dedup.bam
Exception in thread "main" java.lang.IllegalArgumentException: Unknown reference base when restoring base from transition: g, 0
    at net.sf.cram.encoding.read_features.BaseTransitions.getBaseForTransition(BaseTransitions.java:94)
    at net.sf.cram.encoding.read_features.BaseChange.getBaseForReference(BaseChange.java:18)
    at net.sf.cram.CramNormalizer.restoreReadBases(CramNormalizer.java:216)
    at net.sf.cram.CramNormalizer.normalize(CramNormalizer.java:121)
    at net.sf.cram.Cram2Bam.main(Cram2Bam.java:169)
    at net.sf.cram.CramTools.main(CramTools.java:63)

real    0m2.604s
user    0m17.473s
sys 0m0.792s
```
