### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException when no --reference-fasta-file is specified

### ISSUE THREAD

**Issue by ghuls** [vadimzalunin/crammer#8]
Exception in thread "main" java.lang.NullPointerException when no --reference-fasta-file is specified

<code>
$ java -jar cramtools.jar cram --input-bam-file ./PEER-rg.bam --output-cram-file ./PEER.cram
Exception in thread "main" java.lang.NullPointerException
    at net.sf.picard.reference.IndexedFastaSequenceFile.canCreateIndexedFastaReader(IndexedFastaSequenceFile.java:118)
    at uk.ac.ebi.ena.sra.cram.Utils.createIndexedFastaSequenceFile(Utils.java:370)
    at uk.ac.ebi.ena.sra.cram.Bam2Cram.init(Bam2Cram.java:114)
    at uk.ac.ebi.ena.sra.cram.Bam2Cram.main(Bam2Cram.java:445)
    at uk.ac.ebi.ena.sra.cram.CramTools.main(CramTools.java:55)
</code>

**Comment by vadimzalunin** [comment]
I'm afraid this is a feature, not a bug. CRAM is a reference-based compression tool, it always requires a reference sequence file. I'll add a proper message though, thanks!

**Comment by ghuls** [comment]
I know it needs a reference FASTA file, but the current error doesn't make it very obvious. Therefore I reported it.

**Comment by vadimzalunin** [comment]
Oh, sorry! I'll add a check.
