### ISSUE TITLE
ArrayIndexOutOfBoundsException when converting cram to fastq

### ISSUE THREAD

**Issue by anamijalkovic** [vadimzalunin/crammer#80]
Hi Vadim,

I am trying to convert 1000genomes publicly available cram files to the fastq files and I get ArrayIndexOutOfBoundsException. 

For example, for the following file: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/NA06984/alignment/
with following command line: java -jar cramtools/cramtools-2.1.jar fastq -I NA06984.alt_bwamem_GRCh38DH.20150526.low_coverage.bam.cram I get error message: 

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at net.sf.cram.CramTools.invoke(CramTools.java:93)
        at net.sf.cram.CramTools.main(CramTools.java:123)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 57
        at net.sf.cram.structure.Block.<init>(Block.java:50)
        at net.sf.cram.build.CramIO.readSAMFileHeader(CramIO.java:496)
        at net.sf.cram.build.CramIO.readCramHeader(CramIO.java:314)
        at net.sf.cram.Cram2Fastq.main(Cram2Fastq.java:94)
        ... 6 more

Could you please help me solve this problem.

Thank you,
Ana

**Comment by vadimzalunin** [comment]
Hi Ana, 

The repository has been moved to https://github.com/enasequence/cramtools
Please try the latest version with cram3 support: 
https://github.com/enasequence/cramtools/blob/cram3/cramtools-3.0.jar?raw=true

Vadim
